name: Ava web app CI/CD Pipeline

on:
  push:
    branches:
      - Release  # Change to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to ACR
      uses: docker/login-action@v2
      with:
        registry: registry54.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}  # Add ACR username as a secret
        password: ${{ secrets.ACR_PASSWORD }}  # Add ACR password as a secret

    - name: Build and Push Docker Images
      run: |
        docker build -t registry54.azurecr.io/ava-backend-server:latest ./nodejs
        docker push registry54.azurecr.io/ava-backend-server:latest

        docker build -t registry54.azurecr.io/ava-llm-server:latest ./flask
        docker push registry54.azurecr.io/ava-llm-server:latest

        docker build -t registry54.azurecr.io/ava-webapp-frontend:latest ./nextjs
        docker push registry54.azurecr.io/ava-webapp-frontend:latest

    # Authenticate with Azure using Managed Identity
    - name: Azure Login with Managed Identity
      run: |
        az login --identity --username ${{ secrets.AZURE_MANAGED_IDENTITY_CLIENT_ID }}

    # Restart Frontend Web App (ava-frontend)
    - name: Restart Frontend App
      run: |
        az webapp restart --name ava-frontend --resource-group Avaai_group

    # Restart Backend Web App (ava-backend)
    - name: Restart Backend App
      run: |
        az webapp restart --name ava-backend --resource-group Avaai_group

    # Restart LLM Server Web App (ava-llm-server)
    - name: Restart LLM Server App
      run: |
        az webapp restart --name ava-llm --resource-group Avaai_group
